// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Models;

namespace Project1.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20220204221835_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project1.Models.TasksModel", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            Category = "School",
                            Completed = true,
                            Date = new DateTime(2022, 2, 4, 22, 18, 35, 376, DateTimeKind.Utc).AddTicks(8990),
                            Quadrant = 1,
                            Task = "Make the database"
                        },
                        new
                        {
                            TaskID = 2,
                            Category = "Home",
                            Completed = false,
                            Date = new DateTime(2022, 2, 4, 22, 18, 35, 377, DateTimeKind.Utc).AddTicks(440),
                            Quadrant = 2,
                            Task = "Make the Shared Layout"
                        },
                        new
                        {
                            TaskID = 3,
                            Category = "Work",
                            Completed = false,
                            Date = new DateTime(2022, 2, 4, 22, 18, 35, 377, DateTimeKind.Utc).AddTicks(460),
                            Quadrant = 3,
                            Task = "Make the quadrant views"
                        },
                        new
                        {
                            TaskID = 4,
                            Category = "Church",
                            Completed = false,
                            Date = new DateTime(2022, 2, 4, 22, 18, 35, 377, DateTimeKind.Utc).AddTicks(460),
                            Quadrant = 4,
                            Task = "Make the Controllers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
